version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: inaergo
      POSTGRES_PASSWORD: 001pasInaergoQorisdflak
      POSTGRES_DB: apt_inaergo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
