name: Backend Inaergo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setting up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            export PATH="$HOME/.nvm/versions/node/v20.16.0/bin:$HOME/.npm-global/bin:$PATH"
            node -v
            npm -v
            pm2 -v
            cd ~/Documents/backend-inaergo-dev
            git checkout main
            git pull origin main
            git status
            npm ci
            npm run build
            pm2 restart backend-inaergo-dev
