# This is a basic workflow to help you get started with Actions

name: Backend Inaergo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setting up NodeJs
      uses: actions/setup-node@v20
      with:
        node-version: '20'
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        password: ${{ secrets.PASSWORD }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: 22
        script: |
          cd ~/Documents/backend-inaergo-dev
          git checkout main
          git pull origin main
          git status
          npm ci
          npm run build
          pm2 restart backend-inaergo-dev
